version: '3.3'
services:
  rabbit:
    image: rabbitmq:management
    container_name: rabbitmq
#    environment:
#      - RABBITMQ_DEFAULT_USER=guest
#      - RABBITMQ_DEFAULT_PASS=guest
#      - RABBITMQ_DEFAULT_VHOST=/spring-cloud-stream
    ports:
      - "5672:5672"
      - "15672:15672"